### ISSUE TITLE
Feature request: computed

### ISSUE THREAD

**Issue by rcoopr** [luisherranz/deepsignal#17]
I like the DX of using the `signal.value` by default and accessing the underlying signal with the `$` prefix, but context switching when using computed values is awkward. It would be nice to provide `computed` with the same functionality as Preact's `computed`, only returning a proxy object instead for the improved DX

**Comment by luisherranz** [comment]
I'm not sure what you mean. Could you please explain it again using an example?

**Comment by rcoopr** [comment]
Currently, we have

```ts
import { computed, effect } from '@preact/signals-core';
import { deepSignal } from 'deepsignal/core';

const deep = deepSignal({
  a: 5,
  b: 10
})

const multiplied = computed(() => ({
  a: deep.a * 2,
  b: deep.b * 2,
}))

effect(() => {
  // some effect using a combination of deepSignals directly, and computed values
  console.log(deep.a, multiplied.value.a)
  // ^ above, we can use `deep.a` but not `multiplied.a`
})
```

```ts
// proposed:
effect(() => {
  console.log(deep.a, multiplied)
  // accessing multiplied would return the value
  // after all, `computed`s are also signals
})
```

**Comment by rcoopr** [comment]
Some care might need to be given to the case where a `computed` returns a primitive, so the current way of accessing the signal through `obj.$prop` wouldn't work the same

i.e:
```ts
const primitive = computed(() => deep.a * 2)
// `primitive` would return a value, but where is the signal? `primitive.$`?
```

**Comment by luisherranz** [comment]
Is there something wrong with getters? They use `computed` underneath and they'll give you the same `$` API as regular signals:

```js
import { effect } from "@preact/signals-core";
import { deepSignal } from "deepsignal/core";

const deep = deepSignal({
  a: 5,
  b: 10,
});

const multiplied = deepSignal({
  get a() {
    return deep.a * 2;
  },
  get b() {
    return deep.b * 2;
  },
});

effect(() => {
  // this works fine now
  console.log(deep.a, multiplied.a);
});
```

You can also use them in the same object:

```js
import { effect } from "@preact/signals-core";
import { deepSignal } from "deepsignal/core";

const deep = deepSignal({
  a: 5,
  b: 10,
  get doubleA() {
    return deep.a * 2;
  },
  get doubleB() {
    return deep.b * 2;
  },
});
```

Docs: https://github.com/luisherranz/deepsignal#get-prop---

**Comment by rcoopr** [comment]
Sorry, I glossed over that in the docs. I suppose the case where a `computed` returns a primitive is sort of outside the scope for this module dealing with objects

**Comment by luisherranz** [comment]
> I suppose the case where a computed returns a primitive is sort of outside the scope for this module dealing with objects

Do you mean this?

```js
const primitive = computed(() => deep.a * 2)
// `primitive` would return a value, but where is the signal? `primitive.$`?
```

**Comment by rcoopr** [comment]
Yeah

**Comment by luisherranz** [comment]
Then, yeah. If you just have a primitive value, you can't know when it's being written or read. The only exception is Svelte components because they are compiled.

```js
// Solid read
count();
// Solid write
setCount("hi");

// Preact / Vue read
count.value;
// Preact / Vue write
count.value = "hi";

// DeepSignal read
state.count;
// DeepSignal write
state.count = "hi";

// Svelte read
count;
// Svelte write
count = "hi";
// Svelte (final code after compilation)
$$invalidate(0, count = "hi");
```

**Comment by luisherranz** [comment]
Closing now but feel free to reopen if there's anything else that you want to discuss.
