### ISSUE TITLE
"export 'effect' was not found in 'deepsignal'

### ISSUE THREAD

**Issue by ductrieu2719** [luisherranz/deepsignal#18]
Hi,
I am new to deepsignals.
I face this issue when using effect as the example in Readme.md:

> effect(() => {
>      	console.log(state.counter);
> });

Could you pls help to let me know where effect should i import from? Do i need to use effect from Signals along with Deepsignals?

**Comment by luisherranz** [comment]
Yes, if you need `effect`, you need to import it from `@preact/signals` 🙂

```js
import { effect } from "@preact/signals";
```
