### ISSUE TITLE
Enhancement: get informed about insertion/removal of properties

### ISSUE THREAD

**Issue by rozek** [luisherranz/deepsignal#25]
First of all: thank you very much for your marvellous work!

It looks brilliant - but lacks a feature I currently need: I want to get informed whenever a new property is added to an observed object.

After looking into your code, I quickly hacked the required changes in a way I can live with - but these changes are neither properly tested nor completely free of side effects (I'm currently using a "helper property" with a literal key rather than a JavaScript symbol - I did that in order not to touch too many parts of your code)

If you are interested, just have a look into [my fork](https://github.com/rozek/deepsignal) - perhaps, you'll come up with a better (or more professional) solution?

**Comment by rozek** [comment]
I've just added some code for the `ownKeys` Proxy method which eliminates my internal `KeyListSymbol `. Now `Object.keys(store)` produces the expected output...

...but the iterator still does not mention `b`

**Comment by rozek** [comment]
according to [StackOverflow](https://stackoverflow.com/questions/38586471/how-to-control-property-enumeration-for-in-with-proxy-objects), trapping `for...in` seems to be difficult if not impossible...

**Comment by rozek** [comment]
well, I've made some more changes which now also deal with `key in object` and `Object.getOwnPropertyDescriptor` - they all work fine, but the `for ... in` loop doesn't.

```javascript
  console.log(Object.keys(store))

  console.log('a in store','a' in store)
  console.log('b in store','b' in store)
  console.log('c in store','c' in store)
  console.log('* in store',KeyListSymbol in store)

  console.log('a',Object.getOwnPropertyDescriptor(store,'a'))
  console.log('b',Object.getOwnPropertyDescriptor(store,'b'))
  console.log('c',Object.getOwnPropertyDescriptor(store,'c'))
  console.log('*',Object.getOwnPropertyDescriptor(store,KeyListSymbol))
```

**Comment by rozek** [comment]
ok, I got it: I simply had to change the `KeyListSymbol` property *after* setting or defining the new property...

**Comment by luisherranz** [comment]
I made this PR which should add support for things like `for...in` or `Object.keys()`:

- https://github.com/luisherranz/deepsignal/pull/26

**Comment by luisherranz** [comment]
Released as [1.3.2](https://github.com/luisherranz/deepsignal/releases/tag/deepsignal%401.3.2), it would be great if you could test that it works 🙂

**Comment by rozek** [comment]
Good morning!

I found some minutes to test the new version - but, surprisingly, it does NOT work (don't yet know why)

Here is my code

```javascript
  import { deepSignal } from 'deepsignal'

  const store = deepSignal({ a:1 })

  effect(() => {
console.log('------')
    for (const property in store) {
      console.log(`${property}: ${store[property]}`)
    }
  })

console.log('----')
  store.b = 2;
console.log('----')

  console.log('store',store)
```

which produces the following output:

```
------
a: 1
----
----
store Proxy(Object) {a: 1, b: 2}
```

Thus,

* the `effect` is invoked when defined,
* but not when `store.b` is set,
* however, the store finally contains the new property `b`

**Comment by rozek** [comment]
what I found out so far:

* the code itself works as intended `objToIterable.get(target).value++` _is_ invoked
* but that does not recalculate the `effect` body

However, family is calling and I'll have to postpone further investigations until tomorrow...

**Comment by rozek** [comment]
Ok, I got some more minutes and found a solution:

just change the `ownKeys` trap to

```javascript
	ownKeys(target: object): (string | symbol)[] {
		if (!objToIterable.has(target)) objToIterable.set(target, signal(0));
		objToIterable.get(target).value = objToIterable.get(target).value
		return Reflect.ownKeys(target);
	},
```

a simple `objToIterable.get(target).value` is not sufficient (perhaps the compiler optimizes it away?)

But now everything works as intended

**Comment by luisherranz** [comment]
> perhaps the compiler optimizes it away?

It removes the `.value` for some reason.

```js
ownKeys: function (e) {
  return s.has(e) || s.set(e, t.signal(0)), s.get(e), Reflect.ownKeys(e);
},
```

What I don't understand is why [the tests passed fine](https://github.com/luisherranz/deepsignal/actions/runs/5358183066/jobs/9720104055). They are supposed to run against the production build as well.

Anyway, thanks for checking it! I'll fix it on Monday.

**Comment by rozek** [comment]
My own fork is now based on your version 1.3.2 and includes both the bug fix mentioned above and the modifications I need for myself (for `defineProperty` and a property named `$`)

**Comment by luisherranz** [comment]
Cool, thanks.

**Comment by luisherranz** [comment]
Hey @rozek, can you test the latest release?

- https://github.com/luisherranz/deepsignal/releases/tag/deepsignal%401.3.3

> for defineProperty and a property named $

Feel free to open new issues for those to explain the use case of each.

**Comment by luisherranz** [comment]
Great, thanks!

**Comment by rozek** [comment]
As suggested, I've opened two new issues for the enhancements I need
