### ISSUE TITLE
[Bug?] an array nested in an object added to an observed object is not properly observed

### ISSUE THREAD

**Issue by rozek** [luisherranz/deepsignal#34]
It took me quite a while to figure out, but when trying the following code

```javascript
  let hugo = deepSignal({ })
  let anna = hugo.anna = {
    _list:[1,2,3],
    get list () { return this._list.slice() }
  }

  effect(() => { console.log('> anna.list',anna.list) })

  console.log('assign')
    anna._list = anna._list.slice(0,2).concat(2.5,anna._list.slice(2))
    anna._list = anna._list.slice(0,2).concat(anna._list.slice(3))
```

you will see that changes to `anna.list` will not be recognized.

There is, however, a simple workaround: just observe `anna` itself

```javascript
  let anna = hugo.anna = deepSignal({
    _list:[1,2,3],
    get list () { return this._list.slice() }
  })
```

and everything works as intended

**Comment by rozek** [comment]
Perhaps, this issue is not actually a bug in the code, but an unclear documentation:

* `deepSignal(...)` seems to (recursively) convert an object/array and its contents into signals at the time of invocation
* objects/array which are later added to such a converted object/array will have to be converted "manually" (it is with its own explicit `deepSignal(...)` invocation)

**Comment by rozek** [comment]
Ok, things seem to be more complicated:

* first of all, since `slice()` returns a copy (and copies are, by definition, independent of their originals), its result is not observed
* if, however, you want to follow "good programming practices" and not return references to your internal data structures to your clients, you will have to change your programming style and "seal" your internal structures instead - now you can return references rather than copies. This is not a real issue as you cannot change arrays/objects "in-situ" but have to re-assign new versions to observed properties in order for deepSignal to fire

This works fine with a few helper functions:

```javascript
/**** sealed ****/

  function sealed (Candidate) {
    Object.seal(Candidate)
    return Candidate
  }

/**** spliced ****/

  Array.prototype.spliced = function () {
    this.splice.apply(this,Array.prototype.slice.call(arguments))
    return this
  }

  let anna = hugo.anna = deepSignal({
    _list:sealed([1,2,3]),
    get list () { return this._list }
  })

  anna._list = sealed(anna._list.slice().spliced(2,0,2.5))
  anna._list = sealed(anna._list.slice().spliced(2,1))
```

Well, at least until you decide to use classes:

```javascript
  class Berta {
    constructor () {
      this._list = sealed([1,2,3])
    }
    get list () { return this._list }
  }

  let anna = deepSignal(new Berta())

  effect(() => { console.log('> anna.list',anna.list) })

  console.log('assign')
    anna._list = sealed(anna._list.slice().spliced(2,0,2.5))
    anna._list = sealed(anna._list.slice().spliced(2,1))
```

While the `effect` is still invoked upon every change, it always logs an old version of `anna.list` rather than the current one...

**Comment by luisherranz** [comment]
Just do it like this and it'll work fine:

```js
hugo.anna = {
  _list: [1, 2, 3],
  get list() {
    return this._list.slice();
  },
};

let anna = hugo.anna;
```

https://stackblitz.com/edit/vitejs-vite-j7pkwr?file=main.js

The problem is that the proxy is created when it is accessed (`= hugo.anna`), and without the proxy, tracking is not enabled. When you do `let anna = ... = {}` you are referencing the object (target), not the proxy.
