### ISSUE TITLE
Unable to update input field values

### ISSUE THREAD

**Issue by arunmmanoharan** [luisherranz/deepsignal#37]
import * as React from "react";
    import Box from "@mui/material/Box";
    import TextField from "@mui/material/TextField";
    import { useSignal } from "@preact/signals-react";
    import { useDeepSignal } from "deepsignal/react";

    export default function BasicTextFields() {
      const state = useDeepSignal({
        textField1: "",
        textField2: "",
        textField3: ""
      });

      const onHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = event.target;
        state[name] = value;
      };

      return (
        <Box
          component="form"
          sx={{
            "& > :not(style)": { m: 1, width: "25ch" }
          }}
          noValidate
          autoComplete="off"
        >
          <TextField
            name="textField1"
            id="outlined-basic"
            label="Outlined"
            variant="outlined"
            onChange={onHandleChange}
            value={state.$textField1.value}
          />
          <TextField
            name="textField2"
            id="filled-basic"
            label="Filled"
            variant="filled"
            onChange={onHandleChange}
            value={state.$textField2.value}
          />
          <TextField
            name="textField3"
            id="standard-basic"
            label="Standard"
            variant="standard"
            onChange={onHandleChange}
            value={state.$textField3.value}
          />
        </Box>
      );
    }

Why am I not able to update the textField values? I want to have a common changeHandler. Thanks.

This is my stackblitz: https://codesandbox.io/s/affectionate-worker-tkgfqv?file=/demo.tsx:0-1303

**Comment by luisherranz** [comment]
> <TextField
> // ...
> value={state.$textField3}
> />

You can't pass the signal to the `@mui/material/TextField` component because that component is not prepared to receive a signal. [That's explained here in the docs](https://github.com/luisherranz/deepsignal#passing-a-signal-to-a-child-component).

Just pass the value and it works fine:

```js
<TextField
  // ...
  value={state.textField3}
/>
```

[Codesanbox](https://codesandbox.io/s/friendly-river-3f55z7?file%253D%252Fdemo.tsx)
