### ISSUE TITLE
Support for classes

### ISSUE THREAD

**Issue by rozek** [luisherranz/deepsignal#45]
Consider the following code:

```
  import { deepSignal }  from 'https://unpkg.com/deepsignal@1.3.6/dist/deepsignal.module.js'

  class TestClass {
    _Prop = 0

    get Prop () { return this._Prop }
    set Prop (newValue) {
      this._Prop = newValue
      this.logIt()
    }

    logIt () {
      console.log('internal report: Prop was just set to',this.Prop)
    }
  }

  let Test = deepSignal(new TestClass())

/**** now run some tests ****/

  console.log('observe "Test.Prop"')
  effect(() => {
    console.log('>>>> external effect: current "Prop" is now',Test.Prop)
  })

  console.log('\nsetting Test.Prop to 1\n\n')
  Test.Prop = 1

  console.log('\nsetting Test.Prop to 2\n\n')
  Test.Prop = 2
```

(mind the import statement which imports your published module without any of my modifications!)

This code produces the following output:

```
observe "Test.Prop"
>>>> external effect: current "Prop" is now 0
 
setting Test.Prop to 1

>>>> external effect: current "Prop" is now 0
internal report: Prop was just set to 0
>>>> external effect: current "Prop" is now 1

setting Test.Prop to 2

>>>> external effect: current "Prop" is now 1
internal report: Prop was just set to 1
>>>> external effect: current "Prop" is now 2
```

I don't really worry about the useless effect callback invocations for already set values (although they are a bit ugly), but I worry about getter invocations following a set operation which still deliver an old value!

Do you have any idea?

**Comment by rozek** [comment]
I'm currently trying to find the underlying reason for the described (mis)behavior - right now by placing additional `log` statements. The current output

```
setting Test.Prop to 1

set TestClass {_Prop: 0} Prop 1
set TestClass {_Prop: 0} _Prop 1
defineProperty TestClass {_Prop: 0} _Prop {value: 1}
get TestClass {_Prop: 1} Prop Proxy(TestClass) {_Prop: 1}
get TestClass {_Prop: 1} _Prop Proxy(TestClass) {_Prop: 1}
get returns: false 1
get returns: false 0
```

indicates that - given the Getter from `TestClass`

```
get Prop () { return this._Prop }
```

the expression `this._Prop` evaluates properly, but the getter itself returns an outdated value instead...

**Comment by rozek** [comment]
Ok, here is my current hypothesis:

in file [core/src/index.ts](https://github.com/luisherranz/deepsignal/blob/main/packages/deepsignal/core/src/index.ts), after line 78, shouldn't there be an additional line like

```
signals.get(key).value = value
```

perhaps within an `else` clause?

**Comment by rozek** [comment]
my first tests were successful, at least

**Comment by luisherranz** [comment]
Hey @rozek, I think I'm going to prevent the use of classes and only allow plain JS objects. Even if the current fix seems to be just 1-2 lines long, I don't want to start supporting them because that would mean fixing bugs and dealing with edge cases in the future.

Related PR:

- https://github.com/luisherranz/deepsignal/pull/46

**Comment by rozek** [comment]
oh, that's bad because the use of classes is mandatory for me (e.g., because of custom web components)

**Comment by luisherranz** [comment]
What prevents you from using a deepsignal prop inside the class? like `this.state` for example.

**Comment by rozek** [comment]
because users of my classes will only see getters and setters - and these should be reactive

**Comment by luisherranz** [comment]
And what prevents you from using regular objects instead of classes for that purpose?

**Comment by rozek** [comment]
inheritance?

**Comment by luisherranz** [comment]
I see. Well, I'm afraid that you will need to keep maintaining your own fork for the time being as supporting class instances is out of my scope at the moment. I'm sorry about that. I may reconsider it in the future, though.

**Comment by rozek** [comment]
under the hood, JavaScript classes are nothing but constructor functions and property chains - therefore I guess you see problems with these chains...

**Comment by rozek** [comment]
yes, I was thinking about implementing my own variant of nested signals anyway - given the amount of resources I already spent evaluating and tweaking "deepsignals" and "preact-observables" (the latter fails with a very subtle and, thus, extremely nasty race condiction...)

**Comment by rozek** [comment]
but, nevertheless, thank you very much for your work!

**Comment by luisherranz** [comment]
No problem, thanks to you for your contributions to this library @rozek 🙂
