### ISSUE TITLE
Support Maps.

### ISSUE THREAD

**Issue by aspizu** [luisherranz/deepsignal#56]
Cannot proxy a `Map`.
I get,
```ts
Uncaught Error: This object can't be observed.
```

**Comment by luisherranz** [comment]
I don't have plans to support `Map` or `Set` at this moment, but I invite you to create your own `SignalMap`/`SignalSet` library, and use it inside of other deep signals if you want:

```js
import { SignalMap } from "your-signalmap-library";
import { deepSignal } from "deepsignal";

const state = deepSignal({
  someProp: "...",
  someMap: new SignalMap(),
});
```
