### ISSUE TITLE
I have a question about updating the state of a store.

### ISSUE THREAD

**Issue by crazyming9528** [luisherranz/deepsignal#65]
Excuse me, I have a question regarding a specific pattern in a code snippet I'm working with. The code involves a state management setup using deepSignal. 

```
import { deepSignal } from "deepsignal";

const store = deepSignal({
	count: 0,
	get double() {
		return store.count * 2;
	},
	inc: () => {
		store.count += 1;
	},
});

function Counter() {
	return (
		<button onClick={store.inc}>
			{store.$count} x 2 = {store.$double}
		</button>
	);
}  
```
the state (count) is being modified through a method (inc) rather than directly setting the value (e.g., store.count = someValue). I'm curious about the rationale behind this approach. What benefits does using a method like store.inc to update the state provide, as opposed to directly assigning a new value to store.count?

Looking forward to your reply, thank you~

**Comment by luisherranz** [comment]
There is no direct benefit, it's just a way to organize yourself.

I'm going to close the issue, but reopen it if you have any further questions.
