### ISSUE TITLE
Updating a state by assigning an object does not work

### ISSUE THREAD

**Issue by dbilgili** [luisherranz/deepsignal#66]
I have the following state with `deepSignal`

```js
const store = deepSignal({
  user: {
    name: 'Foo',
    age: 20,
  },
});
```

Updating the individual keys works fine

```js
store.user.name = 'Bar'
```

However, assigning a new object -whether spreading the original object or not- does not work. When I try to do this, the state becomes unresponsive, and I can no longer update it by key name, as shown above.

Neither of these approaches work:
```js
store.user = { name: 'Bar', age: 30 }
store.user = { ...store.user, name: 'Bar', age: 30 })
```

My solution was to write a helper function that iterates over the object and updates the key values one by one.

```ts
const updateSignalObject = <T extends object>(
  target: T,
  updates: Partial<{ [K in keyof T]: T[K] }>
): void => {
  Object.entries(updates).forEach(([key, value]) => {
    if (key in target) {
      target[key as keyof T] = value as T[keyof T];
    }
  });
};

updateSignalObject(store.user, { name: 'Bar', age: 30 })
```

Am I missing something, or is this expected behavior?

**Comment by luisherranz** [comment]
It should work fine, so it must be something in the way you're subscribing to the signals.

Can you reproduce the problem in the simplest possible way using StackBlitz? You can use [this template](https://stackblitz.com/edit/vitejs-vite-6qfchy?file=src%2Fmain.jsx) to get started.

**Comment by dbilgili** [comment]
I figured that I was missing the Babel transform package of `@preact/signals-react-transform`, hence the problem. It might be worth mentioning it in the README file for those who uses this package without actually going through the [React integration README](https://github.com/preactjs/signals/blob/main/packages/react/README.md#react-integration) of the `preactjs/signals` package.

**Comment by luisherranz** [comment]
> It might be worth mentioning it in the README file for those who uses this package without actually going through the [React integration README](https://github.com/preactjs/signals/blob/main/packages/react/README.md#react-integration) of the `preactjs/signals` package

It's already mentioned in the readme, in the installation section with React:

- If you want to use `deepSignal` outside of the components, please follow the [React integration guide of `@preact/signals-react`](https://github.com/preactjs/signals/blob/main/packages/react/README.md#react-integration) to choose one of the integration methods.
- For `useDeepSignal`, no integration is required.

https://github.com/luisherranz/deepsignal?tab=readme-ov-file#with-react
